gtnh.settings.blowdryerTag = 0.2.2
modName = GTNH Journey
modId = gtnhjourney
modGroup = dev.gtnhjourney
useModGroupForPublishing = true
autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer
enableModernJavaSyntax = jabel
enableGenericInjection = true
generateGradleTokenClass =
replaceGradleTokenInFile =
apiPackage =
accessTransformersFile =
usesMixins = true
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage = mixin
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false
usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
includeWellKnownRepositories = true
excludeWellKnownRepositories =
usesMavenPublishing = false
modrinthProjectId =
curseForgeProjectId =
org.gradle.configuration-cache = true
org.gradle.parallel = true
